export const COIN_COSTS = {
  MALE_TO_FEMALE_CONNECTION: 2,
  FEMALE_TO_FEMALE_CONNECTION: 2,
  MALE_TO_MALE_CONNECTION: 1,
  FEMALE_TO_MALE_CONNECTION: 1,
  DIRECT_MESSAGE: 1,
};

export const COIN_REWARDS = {
  REFERRAL: 10,
  FEMALE_30_MESSAGES_WITH_MALE: 1,
};

export const UNBLOCK_FINE_COINS = 50;


export const UNBLOCK_FINE = 50;
export const MESSAGE_REWARD_THRESHOLD = 30;